#!/bin/sh
# by tianbaoha

dir=/media/nand/vsftpd
rcf=/opt/etc/init.d/S49vsftpd
export LD_LIBRARY_PATH=$dir

start() {
  mkdir -p /var/run/vsftpd
  $dir/vsftpd $dir/vsftpd.conf &
  ln -sf $dir/start.sh $rcf
  ln -sf /var/log/vsftpd.log $dir/vsftpd.log
}

stop() {
  killall -q vsftpd
  rm -rf $rcf
}

case "$1" in
  start)
    start
  ;;
  stop)
    stop
  ;;
  restart)
    stop
    sleep 1
    start
  ;;
  *)
    echo "Usage: $0 [start stop restart]"
  ;;
esac
